### ISSUE TITLE
Instances can have names with spaces in them, but will always be rebuilt

### ISSUE THREAD

**Issue by LudvikGalois** [shakenfist/terraform-provider-shakenfist#12]
You can create an instance with a name that has a space in it, e.g `"New Machine"`. The space will be stripped and it will be given the name `"NewMachine"`. Upon attempting to reapply the same terraform, it will notice that `"New Machine"` and `"NewMachine"` aren't equal and attempt to rebuild the resource to fix this.

**Comment by mandoonandy** [comment]
This is due to SF sanitising the name to make it safe to use for DNS.
Rather than sanitise and accept, I think SF should reject as invalid any requests with invalid names.
Thoughts @mikalstill ?

**Comment by LudvikGalois** [comment]
In that case it's probably only instances and not resources in general. Let me quickly edit the issue

**Comment by mikalstill** [comment]
So, the issue is DNS ala dnsmasq. We could have two versions of the name? The one provided by the user and then the DNS safe one which is used for dnsmasq / config drive? Would that be bonkers?

**Comment by mandoonandy** [comment]
1. SF is about keeping things simple.
2. Instances are not pets. No pretty names.
