### ISSUE TITLE
Networks and disks are specified differently

### ISSUE THREAD

**Issue by mikalstill** [shakenfist/terraform-provider-shakenfist#16]
Is it weird that networks and disks are specified differently? I feel like its probably my fault...

**Comment by mandoonandy** [comment]
Which "different" are you referring? 
We can't move disks between instances so they are baked into instance configuration. Do we want to be able to move disks between instances one day? If so, they can be broken out now - to avoid too much disruption later. Disks will become a "shareable" resource like networks.

**Comment by mikalstill** [comment]
I more meant this:

```
resource "shakenfist_instance" "sf_1" {
  name   = "sf-1"
  cpus   = 4
  memory = 4096
  disk {
    size = 50
    base = "ubuntu:18.04"
    bus  = "virtio"
    type = "disk"
  }
  networks = [
    "uuid=${shakenfist_network.internal.id},address=192.168.0.11",
  ]
  ssh_key = var.ssh_key
}
```

Disk gets what python would call a dict, but networks get a list of key / value tuples. Or is that because of the list of dicts issue I've half forgotten?
